export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  hce: '/hce',
  enfermeria: '/enfermeria',
  farmacia: '/farmacia',
  afiliaciones: '/afiliaciones',
  admisiones: '/admisiones',
  agendamiento: '/agendamiento',
  portafolio: '/portafolio',
  recaudo: '/recaudo',
  referencias: '/referencias',
  reportes: '/reportes',
  usuarios: '/admin/usuarios',
  roles: '/admin/roles',
  permisos: '/admin/permisos',
} as const;
